source 'http://rubygems.org'

gem 'sinatra'
gem 'rack-flash3'
gem 'activerecord', :require => 'active_record'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'rake'
gem 'require_all'
gem 'sqlite3'
gem 'tux'
gem 'bcrypt'
